{"frames":[{"func":"keras_model_sequential() %>% layer_dense(units = 6, activation = \"sigmoid\", \n    input_shape = ncol(xBiluheld)) %>% compile(loss = \"binary_crossentropy\", \n    optimizer = optimizer_rmsprop(learning_rate = 0.001, rho = 0.9))","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"compile(., loss = \"binary_crossentropy\", optimizer = optimizer_rmsprop(learning_rate = 0.001, \n    rho = 0.9))","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"layer_dense(., units = 6, activation = \"sigmoid\", input_shape = ncol(xBiluheld))","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"create_layer(keras$layers$Dense, object, list(units = as.integer(units), \n    activation = activation, use_bias = use_bias, kernel_initializer = kernel_initializer, \n    bias_initializer = bias_initializer, kernel_regularizer = kernel_regularizer, \n    bias_regularizer = bias_regularizer, activity_regularizer = activity_regularizer,  ...","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"keras$layers","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"`$.python.builtin.module`(keras, \"layers\")","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"py_resolve_module_proxy(x)","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"on_error(result)","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"stop(tf_config()$error_message, call. = FALSE)","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0}],"message":"Error: Valid installation of TensorFlow not found.\n\nPython environments searched for 'tensorflow' package:\n C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python38\\python.exe\n\nPython exception encountered:\n Traceback (most recent call last):\n  File \"C:\\Program Files\\R\\R-4.2.3\\library\\reticulate\\python\\rpytools\\loader.py\", line 119, in _find_and_load_hook\n    return _run_hook(name, _hook)\n  File \"C:\\Program Files\\R\\R-4.2.3\\library\\reticulate\\python\\rpytools\\loader.py\", line 93, in _run_hook\n    module = hook()\n  File \"C:\\Program Files\\R\\R-4.2.3\\library\\reticulate\\python\\rpytools\\loader.py\", line 117, in _hook\n    return _find_and_load(name, import_)\nModuleNotFoundError: No module named 'tensorflow'\n\n\nYou can install TensorFlow using the install_tensorflow() function.\n"}